- name: Create a sandbox instance
  hosts: localhost
  gather_facts: False
  become: False
  tasks:
    - name: Launch instance
      ec2:
        aws_access_key: "{{ ec2_access_key }}"
        aws_secret_key: "{{ ec2_secret_key }}"
        key_name: "{{ ec2_key }}"
        instance_type: "{{ ec2_instance }}"
        image: "{{ ec2_e2_ami }}"
        region: "{{ ohio }}"
        vpc_subnet_id: "{{ ec2_subnet_e2a }}"
#        group: "{{ ec2_e2_sg }}"
        wait: true
        assign_public_ip: yes
        volumes:
          - device_name: "{{ ec2_vol_device }}"
            volume_size: "{{ ec2_vol_size }}" 
            volume_type: gp2
            delete_on_termination: yes
        count_tag: aio
        instance_tags:
          aio: one
        exact_count: 1
      register: ec2

    - name: Add new instance to host group
      add_host: name={{ item.public_ip }} groups=LAUNCHED
      with_items: '{{ec2.instances}}'

    - name: Wait for SSH to come up
      wait_for: host={{ item.public_ip }} port=22 delay=90 timeout=320 state=started
      with_items: '{{ec2.instances}}'

- hosts: all:!localhost
  become: True
  gather_facts: True
  roles:
    - common
    - chris-short.ansible-role-papertrail
    - ntp
    - smtp
    - fail2ban
    - ghost
    - nginx
    - newrelic

- include: datadog.yml

#- hosts: all:!localhost
#  become: True
#  gather_facts: False
#  tasks:
#    - name: Update Everything
#      yum: name=* state=latest

#- hosts: all:!localhost
#  become: True
#  gather_facts: False
#  roles:
#    - yum-cron
