---
# nodejs comes from EPEL
# http://support.ghost.org/supported-node-versions/
# https://github.com/nodejs/LTS
# 
- name: Install Node.js and npm 
  yum: name={{ item }} state=latest
  with_items:
    - nodejs
    - npm

# http://support.ghost.org/installing-ghost-linux/
# https://blog.sahajsoft.com/ansible-play-to-install-ghost-blog-engine-on-ubuntu-server/
- name: Add ghost daemon user
  user: user=ghost state=present system=yes shell=/bin/false createhome=no

- name: Make Ghost Directory
  file: path=/var/www/ghost state=directory mode=0755 owner=ghost group=ghost

- name: Explode Latest Ghost to /var/www/ghost
  unarchive:
    src=https://ghost.org/zip/ghost-latest.zip
    dest=/var/www/ghost
    owner=ghost
    group=ghost
    creates=/var/www/ghost/index.js
    copy=no

- name: Fix ownership on /var/www
  file: path=/var/www owner=root group=root

- name: npm install Ghost
  shell: "cd /var/www/ghost && npm install --production"
  register: ghost_install
  failed_when: ghost_install.rc != 0
  changed_when: false

- name: Instantiate config.js
  template: src=ghost_config.js.j2 dest=/var/www/ghost/config.js owner=ghost group=ghost mode=0664

- name: Install Ghost Orca Theme
  unarchive:
    src=ghost_orca_theme.tgz
    dest=/var/www/ghost/content/themes
    owner=ghost
    group=ghost
    creates=/var/www/ghost/content/themes/orca

- name: Put images in place
  unarchive:
    src=images.tgz
    dest=/var/www/ghost/content/images
    owner=ghost
    group=ghost
    creates=/var/www/ghost/content/images/2015/10/ansible_circleA_blue.png

- name: Bring over database
  copy: src=ghost.db dest=/var/www/ghost/content/data/ghost.db owner=ghost group=ghost mode=0644

# http://support.ghost.org/deploying-ghost/
- name: Install Supervisor
  yum: name=supervisor state=latest

- name: Instantiate ghost supervisord config
  template: src=ghost_supervisor.ini.j2 dest=/etc/supervisord.d/ghost.ini

- name: Start supervisord service
  service: name=supervisord state=started enabled=yes

- name: Start ghost
  supervisorctl: name=ghost state=started
