---
# nodejs comes from EPEL
# http://support.ghost.org/supported-node-versions/
# https://github.com/nodejs/LTS
# 
- name: New Relic Deployment
  newrelic_deployment:
    token={{ nr_api_key }}
    app_name=ghost
    user='ansible ghost deployment'

- name: Install Node.js and npm 
  yum: name={{ item }} state=latest
  with_items:
    - nodejs
    - npm

# http://support.ghost.org/installing-ghost-linux/
# https://blog.sahajsoft.com/ansible-play-to-install-ghost-blog-engine-on-ubuntu-server/
- name: Add ghost daemon user
  user: user=ghost state=present system=yes shell=/bin/false createhome=yes

- name: Make Ghost Directory
  file: path={{ ghost_path }} state=directory mode=0755 owner=ghost group=ghost

- name: Synchronize chrisshort.net backup
  synchronize:
    dest={{ ghost_path }}
    src={{ ghost_backup }}
    recursive=yes
    checksum=yes
    compress=yes

- name: Fix ownership on /var/www
  file: path=/var/www owner=root group=root

- name: Fix ownership on ghost_path
  file: path={{ ghost_path }} owner=ghost group=ghost recurse=yes

- name: npm install Ghost
  shell: "cd {{ ghost_path }} && npm install --production"
  register: ghost_install
  failed_when: ghost_install.rc != 0
  changed_when: false

# http://support.ghost.org/deploying-ghost/
#- name: Install Supervisor
#  yum: name=supervisor state=latest

#- name: Instantiate ghost supervisord config
#  template: src=ghost_supervisor.ini.j2 dest=/etc/supervisord.d/ghost.ini

#- name: Start supervisord service
#  service: name=supervisord state=started enabled=yes

#- name: Start ghost
#  supervisorctl: name=ghost state=started

- name: Install PM2
  npm:
    name: pm2
    global: yes
    version: latest
  notify: restart pm2

- name: Launch Ghost with PM2
  shell: 'NODE_ENV=production pm2 start /var/www/ghost/index.js --name "ghost" -u ghost --hp /home/ghost'

- name: PM2 Startup Script Generation
  shell: pm2 startup systemd
