---
- name: Ensure fail2ban packages are up to date
  yum: name={{ item }} state=latest
  with_items:
    - fail2ban
    - fail2ban-systemd
    - fail2ban-firewalld
    - firewalld
    - selinux-policy*
  tags:
    - fail2ban_pkg

- name: Enable fail2ban and firewalld at system boot
  service: name={{ item }} state=started enabled=yes
  with_items:
    - fail2ban
    - firewalld
  tags:
    - fail2ban_svc

- name: Copy fail2ban jail.local configuration
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=0644
  with_items:
    - { src: 'sshd.local.j2', dest: '/etc/fail2ban/jail.d/sshd.local' }
  notify:
    - restart fail2ban
    - restart firewalld
  tags:
    - fail2ban_conf
