---
- name: Setup yum repos
  yum: name={{ item }} state=present
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm
  when: ansible_distribution == "CentOS"

- name: Add EPEL Repo Key
  rpm_key: state=present key="/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
  tags: key

- name: Install common packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - iptraf
    - man
    - rsync
    - strace
    - sysstat
    - unzip
    - vim
    - wget

- name: Install EL7 packages
  yum: name={{ item }} state=latest
  with_items:
    - net-tools
  when: ansible_distribution == "CentOS" or ansible_distribution == "RedHat" and ansible_distribution_major_version >= 7
