---
- name: Disable sudo requiretty for Ansible pipelining
  lineinfile: dest=/etc/sudoers regexp="^Defaults(\s+)(.*)requiretty(.*)" line="#Defaults\1\2requiretty\3" backrefs=yes

- name: Setup yum repos
  yum: name={{ item }} state=present
  with_items:
    - https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm
    - https://centos{{ ansible_distribution_major_version }}.iuscommunity.org/ius-release.rpm
  when: ansible_distribution == "CentOS"

- name: Add EPEL Repo Key
  rpm_key: state=present key="/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
  tags: key

- name: Install common packages
  yum: name={{ item }} state=latest update_cache=yes
  with_items:
    - curl
    - iptraf
    - libselinux-python
    - lsof
    - man
    - perf
    - python-pip
    - python-virtualenv
    - net-tools
    - rsync
    - rsyslog-gnutls
    - strace
    - sysstat
    - unzip
    - vim
    - wget

- name: Disable SELinux
  selinux: state=disabled

- name: pip install httplib2
  pip: name=httplib2 state=latest

- name: Obtain Papertrail Cert
  get_url: dest=/etc/pki/tls/certs/papertrail-bundle.pem url=https://papertrailapp.com/tools/papertrail-bundle.pem force=yes
  notify: restart rsyslog
  tags: papertrail
  

- name: Deploy rsyslog conf for Papertrail
  template: src=papertrail.conf.j2 dest=/etc/rsyslog.d/papertrail.conf
  notify: restart rsyslog
  tags: papertrail
